### ISSUE TITLE
Podspec should scope GCDWebServer to debug configurations only

### ISSUE THREAD

**Issue by thompsonate** [ConfusedVorlon/HSTestingBackchannel#14]
Setting `:configuration => ['Debug']` in my Podfile for HSTestingBackchannel still installs the dependency GCDWebServer in release builds.

According to the [Cocoapods documentation](https://guides.cocoapods.org/syntax/podspec.html#dependency), you should also be able to scope GCDWebServer to debug builds like so:
`s.dependency 'GCDWebServer', :configurations => ['Debug']`

**Comment by ConfusedVorlon** [comment]
are you able to test/verify and submit a pull request?

I'm swamped at the moment...

**Comment by thompsonate** [comment]
I tested it and I can't get `pod spec lint` to work because it fails to build. It says it's missing GCDWebServer.

This happens even when running `pod spec lint --configuration=DEBUG`, which is odd.

I'm not sure if there is a way around this other than gating the entire functionality of the framework behind `#if DEBUG`.

**Comment by ConfusedVorlon** [comment]
I don't have an answer for that I'm afraid. Might be worth posting on the cocoapods forum (or wherever they hang out)

**Comment by thompsonate** [comment]
I'll look into it. It seems like this is a Cocoapods bug anyway, since there's no reason to include a pod's dependencies in the release configuration if the pod itself is scoped to debug.

**Comment by thompsonate** [comment]
Aha, found the answer on [another documentation page](https://guides.cocoapods.org/syntax/podfile.html#pod).

> Note that transitive dependencies are included in all configurations and you have to manually specify build configurations for them as well in case this is not desired.

So the Readme should probably suggest adding `pod 'GCDWebServer', :configuration => 'Debug'` to the podfile.

**Comment by ConfusedVorlon** [comment]
thanks - I have updated the readme
