### ISSUE TITLE
Detect UI Testing mode at compilation time in Swift

### ISSUE THREAD

**Issue by twestley** [ConfusedVorlon/HSTestingBackchannel#3]
Is there a way to detect UI Testing mode at compilation time in Swift App Delegate?

I have successfully used HSTestingBackchannel in Swift with a bridging header and by detecting it at run time.

In XCTestCase subclass:
```
let app = XCUIApplication()
app.launchArguments = ["-testMode"]
app.launch()

```
In App Delegate:
```
if CommandLine.arguments.contains("-testMode")
{
    HSTestingBackchannel.installReceiver()
}
```
But it appears that the app is run in the Release configuration, so I can't set a preprocessor macro to distinguish it from a real release. In the scheme, Test is set to Debug, but that seems to apply to the XCTestCase code, not the app itself when launched in UI Testing mode.

I fear that importing HSTestingBackchannel in a release configuration will be detected and rejected by Apple at app review.

**Comment by ConfusedVorlon** [comment]
There isn't a way to do this at the moment other than manually setting a flag when you are compiling for snapshot.

I think it should be possible, for snapshot to set a custom build flag - and this has been discussed before.

e.g.:
https://github.com/fastlane/fastlane/issues/2638

also, I'm pretty sure I read that xcode 8 has a new way to set build flags from the command line. I can't find that now.

so: There isn't a way to do this at the moment. To make this work probably requires some digging, and a pull request to Snapshot.

I would be very happy if someone were able to do that - we went round in circles about this some time ago, and did get a launch-time argument
https://github.com/fastlane/fastlane/tree/master/snapshot#launch-arguments
