### ISSUE TITLE
Xcode 9 concurrent_simulators

### ISSUE THREAD

**Issue by jjochen** [ConfusedVorlon/HSTestingBackchannel#6]
With Xcode 9, snapshot can run multiple simulators concurrently (concurrent_simulators). 
But when this is enabled (as it is by default), `HSTestingBackchannel` sends its notifications only to one simulator, all others don't receive anything.

**Comment by ConfusedVorlon** [comment]
thanks for the info. I hadn't thought of that. Snapshot didn't have multiple simulators when I wrote this.

I'm not using this library at the moment, so won't be fixing this any time soon; though of course you're welcome to have a go and send a pull request.

the backchannel works by running a webserver in the simulator. Communication is really simple - just send a message to localhost:SOMEPORT

multiple simulators would make this a lot more complex; you'd need some way to negotiate a channel between each testing process and its appropriate simulator.

**Comment by ConfusedVorlon** [comment]
fixed by
https://github.com/ConfusedVorlon/HSTestingBackchannel/pull/7
