### ISSUE TITLE
Latest podspec not on CocoaPods

### ISSUE THREAD

**Issue by chrischute** [ConfusedVorlon/HSTestingBackchannel#9]
Hi,

I tried using this repo with Snapshot and found out my tests were freezing because of the flag for port numbers. This was fixed in version 1.3.0, but CocoaPods is still hosting 1.2.2. I fixed it by cloning the repo and using a `:path` specifier in my Podfile. Maybe I was doing something wrong, but if not could you please publish version 1.3.0 on CocoaPods?

-Chris

**Comment by ConfusedVorlon** [comment]
thanks for the prod.
iirc, I was hitting some issue with cocoapods when I tried to update last.
Should now be resolved.
